# Ruff 配置
[lint]
ignore = [
    "E402",  # Module import not at top
    "E501",  # Line too long
    "E701",  # Multiple statements (colon)
    "E702",  # Multiple statements (semicolon)  
    "E722",  # Bare except
    "F841",  # Unused variable
]
